---
- hosts: all
  vars:
    server_version: 0.47.0
    rancher_server: "{{ RANCHER_SERVER }}"
    rancher_port: "{{ RANCHER_PORT }}"
    admin_user: "{{ ADMIN_USER }}"
    admin_pass: "{{ ADMIN_PASS }}"
    api_user: "{{ API_USER }}"
    api_pass: "{{ API_PASS }}"
    api_key_body:
      accountId: "1a1"
      description: "provisioner"
      name: "provisioner"
      publicValue: "{{ api_user }}"
      secretValue: "{{ api_pass }}"
      _hack: null
  sudo: yes
  roles:
    - ateoto.docker

  tasks:
  - name: Install httplib2
    apt:
      name: python-httplib2
      update_cache: yes

  - name: Pull and run Rancher server container
    docker:
      name: rancherserver
      image: rancher/server:v{{ server_version }}
      state: reloaded
      restart_policy: always
      detach: True
      ports:
      - "{{ rancher_port }}:{{ rancher_port }}"

  - name: Wait for the Rancher server to start
    action: command docker logs rancherserver
    register: rancher_logs
    until: rancher_logs.stdout.find("Listening on") != -1
    retries: 30
    delay: 10

  - name: Add API access key to admin account
    uri:
      method: POST
      status_code: 201
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/apikeys"
      body_format: json
      body: "{{ api_key_body | to_json }}"

  - name: Enable local authentication and setup rancher server admin user
    uri:
      method: POST
      status_code: 201
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/localauthconfigs"
      body_format: json
      body: "{ \"accessMode\": \"restricted\", \"enabled\": true, \"name\": \"{{ admin_user }}\", \"password\": \"{{ admin_pass }}\", \"username\": \"{{ admin_user }}\" }"

  - name: Confirm admin access to API
    uri:
      method: GET
      status_code: 200
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1"