---
- hosts: all
  vars:
    server_version: 0.47.0
    rancher_server: "{{ RANCHER_SERVER }}"
    rancher_port: "{{ RANCHER_PORT }}"
    admin_user: "{{ ADMIN_USER }}"
    admin_pass: "{{ ADMIN_PASS }}"
  sudo: yes
  roles:
    - ateoto.docker

  tasks:
  - name: Install httplib2
    apt:
      name: python-httplib2
      update_cache: yes

  - name: Pull and run Rancher server container
    docker:
      name: rancherserver
      image: rancher/server:v{{ server_version }}
      state: reloaded
      restart_policy: always
      detach: True
      ports:
      - "{{ rancher_port }}:{{ rancher_port }}"

  - name: Wait for the Rancher server to start
    action: command docker logs rancherserver
    register: rancher_logs
    until: rancher_logs.stdout.find("Listening on") != -1
    retries: 30
    delay: 10

  - name: Setup admin user
    uri:
      method: POST
      status_code: 201
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/localauthconfigs"
      body_format: json
      body: "{ \"accessMode\": \"restricted\", \"enabled\": true, \"name\": \"{{ admin_user }}\", \"password\": \"{{ admin_pass }}\", \"username\": \"{{ admin_user }}\" }"
  
  - name: Set default environment
    uri:
      method: POST
      status_code: 201
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/userpreference"
      body_format: json
      body: "{\"type\":\"userPreference\",\"name\":\"defaultProjectId\",\"value\":\"1a5\"}"

  - name: Confirm admin access
    uri:
      method: GET
      status_code: 200
      force_basic_auth: yes
      user: "{{ admin_user }}"
      password: "{{ admin_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/projects"
