---
- hosts: all
  vars:
    rancher_server_version: 0.47.0
  sudo: yes
  roles:
    - ateoto.docker
  tasks:
  - name: Pull and run Rancher server container
    docker:
      name: rancherserver
      image: rancher/server:v{{rancher_server_version}}
      state: reloaded
      restart_policy: always
      detach: True
      ports:
      - "{{ rancher_port }}:{{ rancher_port }}"

  - name: Wait for the Rancher server to start
    action: command docker logs rancherserver
    register: rancher_logs
    until: rancher_logs.stdout.find("Listening on") != -1
    retries: 30
    delay: 10

